### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by Frostbow23** [ShineUA/minecraft-splash-mod-geode#8]
### Select your platform

Windows

### Describe your issue

Tried adding a splash text and it crashed my game

[2024-06-24_01-04-32.log](https://github.com/user-attachments/files/15950105/2024-06-24_01-04-32.log)

### Steps to reproduce the bug

Add new splash
entered "Silent In The Clubstep"
0.5 size
Apply
Go to menu

### Extra fields

- [X] I updated Geode to latest version.
- [X] I updated Geode Launcher (Android) to latest version.
- [X] I updated this mod to latest version.

**Comment by sh1ne-dev** [comment]
Try reinstalling this mod with "Delete mod's save data" checkbox enabled.
